---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgres
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresql
      version: 12.1.14
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    global:
      postgresql:
        auth:
          postgresPassword: "${POSTGRESQL_ADMIN_PASSWD}"
          username: ${POSTGRESQL_USER}
          password: "${POSTGRES_USER_PASSWD}"
          database: superdb
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: "15.1.0"
    primary:
      persistence:
        enabled: true
        type: pvc
        mountPath: /var/lib/pgsql/data
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 5Gi
        retain: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
