---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 10.0.1.10
        k8s-1:
          ansible_host: 10.0.1.11
        k8s-2:
          ansible_host: 10.0.1.12
    worker:
      hosts:
        k8s-3:
          ansible_host: 10.0.1.13
        k8s-4:
          ansible_host: 10.0.1.14
        k8s-5:
          ansible_host: 10.0.1.15
