apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:dYJT9QjF31Tn5mbulPgud5E=,iv:5qtBAExHGLsMJnQ+/dJUcWhbHSz0m1Wo9aKqBEGEPfY=,tag:YWgYY/8sGZqpW6LRQPm08g==,type:str]
    api-key: ENC[AES256_GCM,data:H9eKnt5ss+mCJE4otaCwF1P0qfiawva89mEjsyfoNSHDvTGldg==,iv:wOh0Fb6W4faZcuCPh2vtZ7x6uZH3k24HOYJjY29FZDQ=,tag:baxD9swDP7OXXOPAmJjITw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qse48f7zg243dxr64quuw26y9ep8yax204rzvy8etq52adwf0g6qcxjx6h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZEtBVjg1RXdmVTJsWVNQ
            Lzdad1c4TUFjMGlLelRUMzVZenhnek9Jemk4ClhrdjJCOHFQV3B2aXlDWWFuNmhB
            dkM0Q3cwbDlHNUdrNjVOa0ova3E4MU0KLS0tIEZjVGVLMzVNSDVUSXIwdnpBZzZO
            eVFhMWxYWjM3MU1oTm5hZTJqaFlaNWcKTYlEETydpQ8pCbvNsIi8+sR/JvJyvt+b
            zA28cpbeTpB+UNtjZNHtdkRX1PkSNhgN81pmoR5nbE2jpNa4XFriWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-04T21:32:08Z"
    mac: ENC[AES256_GCM,data:1VLeILs4+/hC2zDBXqyEsOHZLX6VHWPDEZgUUISZGqvqOV5WRPJ2pumwGMJ3o2gyoldciTC6c3R4ITLAx/Vpa+pCv2Mmt4mf4dqe4evmFAJQoa0zdiy8bRWLYLi+i4/YWCfFPQWXd99gyY37RbClfoVsYc9UGpjf9p/LkNLPv9c=,iv:CK1D0hVuCAChKpOz8R21UMjjni4l6LGN6coe1GmcST0=,tag:+K7MpiadQH1ALfdkkXdGaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
