---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./echo-server/ks.yaml
  - ./hajimari/ks.yaml
  - ./libreddit/ks.yaml
  - ./jellyfin/ks.yaml
  - ./minecraft-server/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
