---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: archtest
  namespace: default
spec:
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: archlinux/archlinux
      tag: latest

    persistence:
      data:
        enabled: true
        mountPath: /storage/media
        path: /tank/torrents
        server: 10.0.0.100
        type: nfs
