---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app libreddit
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      replicas: 1
    fullNameOverride: *app
    image:
      repository: ghcr.io/auricom/libreddit
      tag: 0.29.3@sha256:f9a4f9c15d73e93549b6982a83fdb80a229e471b547c1dbc0a26a6e00ecc3e5b
    env:
      LIBREDDIT_DEFAULT_SHOW_NSFW: true
      LIBREDDIT_DEFAULT_WIDE: true
    service:
      main:
        ports:
          http:
            port: &port 8080
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.home.arpa/enabled: "false"
          auth.home.arpa/enabled: "false"
          hajimari.io/icon: simple-icons:reddit
        hosts:
          - host: &host "libreddit.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /settings
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    resources:
      requests:
        cpu: 5m
        memory: 50Mi
      limits:
        memory: 250Mi
