---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: radarr-configmap
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
commonLabels:
  app.kubernetes.io/name: radarr
  app.kubernetes.io/instance: radarr
