---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Vancouver"
  KUBE_VIP_ADDR: "10.0.1.9"
  METALLB_LB_RANGE: "10.0.1.20-10.0.1.150"
  METALLB_K8S_GATEWAY_ADDR: "10.0.1.20"
  METALLB_INGRESS_ADDR: "10.0.1.21"
