---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2
      reclaimPolicy: Retain
    defaultSettings:
      createDefaultDiskLabeledNodes: true
      defaultDataLocality: best-effort
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      storageMinimalAvailablePercentage: 10
      defaultReplicaCount: 2
      defaultLonghornStaticStorageClass: longhorn
    ingress:
      enabled: true
      host: "longhorn.${SECRET_DOMAIN}"
      path: /
      tls: true
      tlsSecret: longhorn
      annotations:
        coredns.io/hostname: "longhorn.${SECRET_DOMAIN}"
        cert-manager.io/cluster-issuer: letsencrypt-production
        kubernetes.io/ingress.class: nginx
        hajimari.io/enable: "true"
        hajimari.io/icon: cow
        hajimari.io/group: storage
        hajimari.io/appName: longhorn
