---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: minecraft-server
  app.kubernetes.io/instance: minecraft-server
